INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Sketching Tin", "Art", 10000, 4/1/2017, 8/26/17);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Change Is Good", "Design", 137000, 2/19/2017, 9/1/17);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Realm of Colors", "Games", 14000, 3/17/2017, 12/22/17);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Luna Display", "Technology", 400000, 7/8/2017, 11/10/17);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Steamroller", "Music", 4000, 5/12/2017, 7/12/17);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Desserts in Duvets", "Food", 50000, 6/2/2017, 9/18/17);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Orbital Reflector", "Art", 200000, 5/10/2017, 10/5/17);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ink the Earth", "Art", 10000, 7/22/2017, 9/15/17);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Layers Clothing", "Fashion", 12000, 6/13/2017, 10/13/17);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("LifeTimes Magazine", "Journalism", 5500, 7/1/2017, 12/31/17);

INSERT INTO users (name, age) VALUES ("Victoria", 57);
INSERT INTO users (name, age) VALUES ("Matt", 27);
INSERT INTO users (name, age) VALUES ("Vincent", 25);
INSERT INTO users (name, age) VALUES ("Angela", 39);
INSERT INTO users (name, age) VALUES ("Diane", 39);
INSERT INTO users (name, age) VALUES ("Bob", 63);
INSERT INTO users (name, age) VALUES ("Lauren", 31);
INSERT INTO users (name, age) VALUES ("Reed", 36);
INSERT INTO users (name, age) VALUES ("Jonathan", 28);
INSERT INTO users (name, age) VALUES ("Sebastian", 22);
INSERT INTO users (name, age) VALUES ("Daniel", 43);
INSERT INTO users (name, age) VALUES ("Kathryn", 32);
INSERT INTO users (name, age) VALUES ("Anthony", 71);
INSERT INTO users (name, age) VALUES ("Brittany", 24);
INSERT INTO users (name, age) VALUES ("Rina", 26);
INSERT INTO users (name, age) VALUES ("Jason", 55);
INSERT INTO users (name, age) VALUES ("Helen", 35);
INSERT INTO users (name, age) VALUES ("Amber", 29);
INSERT INTO users (name, age) VALUES ("Michael", 30);
INSERT INTO users (name, age) VALUES ("Cara", 23);



INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 14, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (220, 13, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 8, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (460, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (310, 9, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 6, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (410, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (560, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (820, 10, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (425, 20, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (125, 11, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 3, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1500, 15, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (550, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1200, 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (130, 16, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 4, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (850, 19, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (775, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 17, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (340, 5, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (415, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (280, 18, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 6, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 2, 7);
